extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  windowsperfcounters:
    collection_interval: 1s
    perfcounters:
      - object: "Memory"
        counters:
          - "Committed Bytes"

exporters:
  logging:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
      exporters: [prometheus, logging]

  extensions: [zpages]
